# Generated by Django 4.1.1 on 2022-10-24 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contestant',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_photo', models.ImageField(default='default.png', upload_to='')),
                ('dateOfBirth', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
