# Generated by Django 4.1.1 on 2022-10-17 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0003_alter_user_profile_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('contest_name', models.CharField(max_length=20)),
                ('contest_date', models.IntegerField(max_length=10)),
                ('contest_url', models.URLField(max_length=50, primary_key=True, serialize=False)),
                ('user_contestSites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.user_profile')),
            ],
        ),
    ]
