# Generated by Django 4.1.1 on 2022-10-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_ID', models.IntegerField(max_length=10)),
                ('user_email', models.EmailField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
                ('contestSites_ID', models.CharField(max_length=20)),
                ('user_contestSites', models.CharField(max_length=20)),
            ],
        ),
    ]
