# Generated by Django 4.1.1 on 2022-10-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_user_profile_id_alter_user_profile_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='user_ID',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='user_name',
            field=models.CharField(max_length=30),
        ),
    ]
